# Generated by Django 2.0.5 on 2018-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotpreferred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
