# Generated by Django 2.0.5 on 2018-06-18 13:09

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotpreferred', '0003_auto_20180611_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
